name: PHP CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  code-style:
    name: Code style
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php-versions: ['8.1']
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2

      - name: Check PHP Version
        run: php -v

      - name: Update dependencies with composer
        run: composer update --no-interaction --no-ansi --no-progress

      - name: Run ECS
        run: composer check-style

  static-analysis:
    name: Static analysis (PHPStan)
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php-versions: ['8.1']
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2

      - name: Check PHP Version
        run: php -v

      - name: Update dependencies with composer
        run: composer update --no-interaction --no-ansi --no-progress

      - name: Run Static Analysis
        run: composer static-analysis

  unit-tests:
    name: Unit tests
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php-versions: ['8.1', '8.2']
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2

      - name: Check PHP Version
        run: php -v

      - name: Update dependencies with composer
        run: composer update --no-interaction --no-ansi --no-progress

      - name: Run PHPUnit
        run: XDEBUG_MODE=coverage composer unit-test